spring:
  application:
    name: referentiel-api-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/klem_trade_x}
    username: ${DB_USERNAME:referentiel_api}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: klem_trade_x
    open-in-view: false
  flyway:
    locations: classpath:db/migration
    schemas: klem_trade_x
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI}

server:
  port: ${SERVER_PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
